### ISSUE TITLE
CREATE NETWORK CONFIG AS CR

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/clusterbook#9]
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkconfigs.example.com
spec:
  group: example.com
  names:
    kind: NetworkConfig
    listKind: NetworkConfigList
    plural: networkconfigs
    singular: networkconfig
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                networks:  # Corrected property name from 'newtorks' to 'networks'
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: string
---
apiVersion: example.com/v1
kind: NetworkConfig
metadata:
  name: networks-labul
  namespace: default  # Ensure this is the correct namespace
spec:
  networks:  # Corrected property name from 'newtorks' to 'networks'
    "10.31.103":
      - "3:assigned:sandiego"
      - "4"
    "10.31.104":
      - "8:pending:miami"
      - "10"
      - "11"
```

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"k8s.io/apimachinery/pkg/api/errors"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
)

// Define the NetworkConfig struct
type NetworkConfig struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          NetworkConfigSpec `json:"spec,omitempty"`
}

type NetworkConfigSpec struct {
	Networks map[string][]string `json:"networks"`
}

// Create the Custom Resource GroupVersion
var groupVersion = schema.GroupVersion{Group: "example.com", Version: "v1"}
var resource = "networkconfigs"

// Function to create a Kubernetes client
func createK8sClient() (*kubernetes.Clientset, error) {
	kubeconfig := os.Getenv("KUBECONFIG")
	if kubeconfig == "" {
		kubeconfig = os.Getenv("HOME") + "/.kube/fluxdev-3"
	}

	config, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
	if err != nil {
		return nil, err
	}

	return kubernetes.NewForConfig(config)
}

// Function to create a dynamic client for CRDs
func createDynamicClient(config *rest.Config) (dynamic.Interface, error) {
	return dynamic.NewForConfig(config)
}

// Function to create a NetworkConfig resource
func createOrUpdateNetworkConfig(ns string, networkConfig *NetworkConfig) error {
	// Build the Kubernetes config
	kubeConfig, err := clientcmd.BuildConfigFromFlags("", os.Getenv("KUBECONFIG"))
	if err != nil {
		return err
	}

	// Create a dynamic client using the config
	dynClient, err := createDynamicClient(kubeConfig)
	if err != nil {
		return err
	}

	// Convert the NetworkConfig struct to an unstructured format
	unstructuredConfig, err := runtime.DefaultUnstructuredConverter.ToUnstructured(networkConfig)
	if err != nil {
		return err
	}

	// Set the group version resource
	resourceClient := dynClient.Resource(groupVersion.WithResource(resource)).Namespace(ns)

	// Try to update the resource if it already exists
	existingResource, err := resourceClient.Get(context.TODO(), networkConfig.Name, v1.GetOptions{})
	if err != nil {
		if errors.IsNotFound(err) {
			// If not found, create a new one
			_, err = resourceClient.Create(context.TODO(), &unstructured.Unstructured{
				Object: unstructuredConfig,
			}, v1.CreateOptions{})
			return err
		}
		return err // Handle other errors
	}

	// If it exists, update the resource
	unstructuredConfig["metadata"] = existingResource.Object["metadata"] // Retain the existing metadata (e.g., UID, resource version)
	_, err = resourceClient.Update(context.TODO(), &unstructured.Unstructured{
		Object: unstructuredConfig,
	}, v1.UpdateOptions{})
	return err
}

// Function to get a NetworkConfig resource
func getNetworkConfig(ns, name string) (*NetworkConfig, error) {
	// Build the Kubernetes config
	kubeConfig, err := clientcmd.BuildConfigFromFlags("", os.Getenv("KUBECONFIG"))
	if err != nil {
		return nil, err
	}

	// Create a dynamic client using the config
	dynClient, err := createDynamicClient(kubeConfig)
	if err != nil {
		return nil, err
	}

	// Retrieve the resource
	resourceClient := dynClient.Resource(groupVersion.WithResource(resource)).Namespace(ns)
	unstructuredConfig, err := resourceClient.Get(context.TODO(), name, v1.GetOptions{})
	if err != nil {
		return nil, err
	}

	// Convert the unstructured data back to NetworkConfig struct
	var networkConfig NetworkConfig
	err = runtime.DefaultUnstructuredConverter.FromUnstructured(unstructuredConfig.Object, &networkConfig)
	return &networkConfig, err
}

func main() {
	// clientset, err := createK8sClient()
	// if err != nil {
	// 	log.Fatalf("Failed to create Kubernetes client: %v", err)
	// }

	// Define the NetworkConfig resource
	networkConfig := &NetworkConfig{
		TypeMeta: v1.TypeMeta{
			APIVersion: groupVersion.String(),
			Kind:       "NetworkConfig",
		},
		ObjectMeta: v1.ObjectMeta{
			Name:      "networks-labul-2",
			Namespace: "default",
		},
		Spec: NetworkConfigSpec{
			Networks: map[string][]string{
				"10.31.103": {
					"3:assigned:sandiego",
					"4",
				},
				"10.31.104": {
					"8:pending:miami",
					"10",
					"11:pending:neyyork",
				},
			},
		},
	}

	// Create the NetworkConfig resource
	err := createOrUpdateNetworkConfig("default", networkConfig)
	if err != nil {
		log.Fatalf("Failed to create NetworkConfig: %v", err)
	}

	fmt.Println("NetworkConfig created successfully!")

	// Retrieve the NetworkConfig resource
	retrievedConfig, err := getNetworkConfig("default", "networks-labul-2")
	if err != nil {
		log.Fatalf("Failed to get NetworkConfig: %v", err)
	}

	// Output the retrieved config
	jsonOutput, _ := json.MarshalIndent(retrievedConfig, "", "  ")
	fmt.Printf("Retrieved NetworkConfig: %s\n", jsonOutput)
}
```
